### ISSUE TITLE
PPPC script doesn't write valid plist data

### ISSUE THREAD

**Issue by poundbangbash** [carlashley/munkicon#3]
Running the PPPC script doesn't write out proper plist data.
An example of the complete ConditionalItems.plist after running the script is:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>pppcp_payloads</key>
	<array>
		<string>/Library/Application Support/Tablet/WacomTabletSpringboard</string>
		<string>com.apple.fdesetup</string>
		<string>com.bomgar.bomgar-scc</string>
		<string>com.wacom.WacomTouchDriver</string>
		<string>com.apple.systemsetup</string>
		<string>com.apple.screensharing.agent</string>
```

**Comment by carlashley** [comment]
This should be corrected now.

**Comment by poundbangbash** [comment]
I'm still seeing it write the client data out but it doesn't close out the plist format.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/1416288/96671909-95eeb200-1328-11eb-8d86-f86fdcd86f8d.png">

**Comment by poundbangbash** [comment]
Looks like it's catching a `None` as an Identifier and the plist write is failing at that point.  
Adding `if _identifier is not None:` in around line 33 addressed it here in testing.  The output is now valid plist format.
```_identifier = _values.get('Identifier', None)
                        if _identifier is not None:
                            _result.add(_identifier)
```
